### ISSUE TITLE
az ssh command doesn't work due to OpenSSH not being installed in the docker container

### ISSUE THREAD

**Issue by Gilthans** [Azure/cli#146]
Trying to use `az ssh vm` with this action does not work, and fails with:
```
WARNING: The command requires the extension ssh. It will be installed first.
WARNING: Default enabled including preview versions for extension installation now. Disabled in May 2024. Use '--allow-preview true' to enable it specifically if needed. Use '--allow-preview false' to install stable version only. 
ERROR: Failed to run ssh command with error: [Errno 2] No such file or directory: 'ssh'.
```
Attempting to install OpenSSH inside the inline script didn't seem to resolve the issue.
Is there a way to get this working?

**Comment by MoChilia** [comment]
Hi @Gilthans, have you added the `ssh` extension with `az extension add --name ssh` before trying `az ssh vm`?

**Comment by Gilthans** [comment]
I did not, but the tool was trying to install the extension automatically which is when it failed

**Comment by MoChilia** [comment]
@Gilthans, according to https://github.com/Azure/azure-cli/issues/27841#issuecomment-1809942182, azure-cli has removed `ssh` from the docker image since `2.54.0`, you have to install it manually. If you have already installed OpenSSH but the error persists, you can try using the argument `--ssh-client-folder` to provide the OpenSSH folder path.

**Comment by MoChilia** [comment]
Closing the issue for now. If you have any further questions, feel free to reopen it.
